# Variable 'azureml.resourceGroup' was defined in the Variables tab
# Variable 'azureml.workspaceName' was defined in the Variables tab
# Variable 'aks.clusterName' was defined in the Variables tab
# Variable 'aks.vmSize' was defined in the Variables tab
# Variable 'agentCount' was defined in the Variables tab
# Variable 'service.name.production' was defined in the Variables tab
jobs:
- job: Job
  displayName: Agent job
  pool:
    vmImage: ubuntu-20.04
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: 3.8
steps:
- task: AzureCLI@2
  displayName: 'Add Azure ML CLI'
  inputs:
    azureSubscription: ServiceConnection2
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'
steps:
- task: AzureCLI@2
  displayName: 'Create AKS Cluster'
  inputs:
    azureSubscription: ServiceConnection2
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az ml computetarget create aks -g $(azureml.resourceGroup) -w $(azureml.workspaceName) -n $(aks.clusterName) -s $(aks.vmSize) -a $(aks.agentCount)
steps:
- task: AzureCLI@2
  displayName: 'Deploy to AKS'
  inputs:
    azureSubscription: ServiceConnection2
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az ml model deploy -g $(azureml.resourceGroup) -w $(azureml.workspaceName) -n $(service.name.production) -f ../metadata/model.json --dc aksDeploymentConfig.yml --ic inferenceConfig.yml --ct $(aks.clusterName) --overwrite