name: training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.8.10
- pip=21.1.1
- pip:
  - azureml-defaults
  - ktrain
  - tensorflow
  - torch
  - onnx
  - onnxruntime